/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Eliminar;

import Componentes.FrameRecrea;
import Componentes.PanelRecrea;
import Contrato.ContratoBotones;
import Contrato.ContratoGeneral;
import Controller.ControllerConsultar;
import Controller.ControllerEliminar;
import Controller.Util;
import Model.Objetos.Leccion;
import Model.Objetos.Materia;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Manuel Goncalves L.
 */
public class EliminarLeccion extends FrameRecrea implements ContratoBotones {

    private final PanelRecrea pnRecrea;
    private final ContratoGeneral contGen;
    private final ControllerConsultar cc;
    private final ControllerEliminar ce;
    private Leccion leccion;
    private Materia materia;
   // private final String seleccionar=Util.COMBOBOX_SELECCIONAR;
    /**
     * Creates new form EliminarLeccion
     * @param cg contratoGeneral de la interfaz padre
     */
    public EliminarLeccion(ContratoGeneral cg) {
        pnRecrea=new Componentes.PanelRecrea();
        cc=new ControllerConsultar();
        ce=new ControllerEliminar();
        contGen=cg;
        initComponents();
        contGen.SetEnable(false);
        this.add(pnRecrea);
        this.configuracion(pnRecrea);
        CB_Materia=cc.CargarComboBoxMateria(CB_Materia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_Titulo1 = new Componentes.LabelRecrea();
        LB_TItulo2 = new Componentes.LabelRecrea();
        CB_Materia = new Componentes.ComboBoxRecrea();
        CB_Leccion = new Componentes.ComboBoxRecrea(Util.COMBOBOX_SELECCIONAR);
        NB_Nivel = new Componentes.NumberBoxRecrea();
        BT_Imagen = new Componentes.BotonRecrea();
        BT_Borrar = new Componentes.BotonRecrea(Util.BOTON_TIPO_SEGUIR,this);
        BT_Cancelar = new Componentes.BotonRecrea(Util.BOTON_TIPO_SALIR,this);
        LB_Materia = new Componentes.LabelRecrea();
        LB_Leccion = new Componentes.LabelRecrea();
        LB_Nivel = new Componentes.LabelRecrea();
        LB_Imagen = new Componentes.LabelRecrea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        LB_Titulo1.setText("Seleccione la lección");

        LB_TItulo2.setText("que desea borrar");

        CB_Materia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_MateriaItemStateChanged(evt);
            }
        });

        CB_Leccion.setEnabled(false);
        CB_Leccion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_LeccionItemStateChanged(evt);
            }
        });

        NB_Nivel.setEnabled(false);

        BT_Borrar.setText("Borrar");

        BT_Cancelar.setText("Cancelar");

        LB_Materia.setText("Materia");

        LB_Leccion.setText("Lección");

        LB_Nivel.setText("Nivel");

        LB_Imagen.setText("Imagen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(LB_TItulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BT_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BT_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(LB_Materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LB_Leccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LB_Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LB_Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BT_Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CB_Materia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CB_Leccion, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(NB_Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(LB_Titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(LB_Titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LB_TItulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CB_Materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_Materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CB_Leccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_Leccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NB_Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT_Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BT_Borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CB_MateriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_MateriaItemStateChanged
       materia=(Materia)this.CB_Materia.GetItemRecrea();
       if(CB_Materia.getSelectedIndex()>0)
      {
        cc.CargarComboBoxLeccion(CB_Leccion,materia);
        CB_Leccion.setEnabled(true);
      }
      else 
      {
          CB_Leccion.setEnabled(false);
          CB_Leccion.setSelectedIndex(0);
      }
    }//GEN-LAST:event_CB_MateriaItemStateChanged

    private void CB_LeccionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_LeccionItemStateChanged
     
      leccion=(Leccion)this.CB_Leccion.GetItemRecrea();
      this.NB_Nivel.setText(Integer.toString(leccion.getNivel()));
      this.BT_Imagen.BotonConfig(leccion.getImagenURL(),leccion.getNombre());
      this.BT_Imagen.setRolloverIcon(null);
    }//GEN-LAST:event_CB_LeccionItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Componentes.BotonRecrea BT_Borrar;
    private Componentes.BotonRecrea BT_Cancelar;
    private Componentes.BotonRecrea BT_Imagen;
    private Componentes.ComboBoxRecrea CB_Leccion;
    private Componentes.ComboBoxRecrea CB_Materia;
    private Componentes.LabelRecrea LB_Imagen;
    private Componentes.LabelRecrea LB_Leccion;
    private Componentes.LabelRecrea LB_Materia;
    private Componentes.LabelRecrea LB_Nivel;
    private Componentes.LabelRecrea LB_TItulo2;
    private Componentes.LabelRecrea LB_Titulo1;
    private Componentes.NumberBoxRecrea NB_Nivel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ActionSiguiente(ActionEvent e) {
        if(ce.EliminarLeccion(leccion, materia))
             JOptionPane.showMessageDialog(this,Util.MENSAJE_LECCION_BORRADA, Util.DIALOG_TITULO_MENSAJE, JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(this,Util.ERROR_OPERACION_FALLIDA, Util.DIALOG_TITULO_MENSAJE, JOptionPane.INFORMATION_MESSAGE);
       
    ActionSalir(e);
    }

    @Override
    public void ActionSalir(ActionEvent e) {
      
        this.setVisible(false);
        contGen.SetEnable(true);
        this.dispose(); }

    @Override
    public void ActionOpciones(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void ActionSonido(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
