/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Componentes.PanelRecrea;
import Componentes.TextBoxRecrea;
import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author Manuel Goncalves L.
 */
public class AgregarUsuario extends Componentes.FrameRecrea {

    /**
     * Creates new form AgregarUsuario
     */
    private PanelRecrea panelP =new PanelRecrea();
    
    public AgregarUsuario() {
        
        initComponents();
        this.add(panelP);
        this.configuracion(panelP);
        TF_Nombre= new JTextField("HOLA");
        TF_Nombre.replaceSelection("Hisufb");
        TF_Nombre.setText("HOLA2");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TF_Nombre = new javax.swing.JTextField();
        TF_Apellido = new javax.swing.JTextField();
        LB_Bienvenido1 = new javax.swing.JLabel();
        LB_Bienvenido2 = new javax.swing.JLabel();
        LB_Bienvenido3 = new javax.swing.JLabel();
        LB_Nombre = new javax.swing.JLabel();
        LB_Apellido = new javax.swing.JLabel();
        BT_Comenzar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TF_Nombre.setToolTipText("jbhbhbj");

        TF_Apellido.setToolTipText("jnjnj");

        LB_Bienvenido1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LB_Bienvenido1.setForeground(new java.awt.Color(255, 255, 255));
        LB_Bienvenido1.setText("Bienvenido a Recrea el lugar donde");

        LB_Bienvenido2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LB_Bienvenido2.setForeground(new java.awt.Color(255, 255, 255));
        LB_Bienvenido2.setText("tu y yo practicaremos matemáticas");

        LB_Bienvenido3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LB_Bienvenido3.setForeground(new java.awt.Color(255, 255, 255));
        LB_Bienvenido3.setText("¡Empezemos!");

        LB_Nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LB_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        LB_Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB_Nombre.setText("¿Como te llamas?");

        LB_Apellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LB_Apellido.setForeground(new java.awt.Color(255, 255, 255));
        LB_Apellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB_Apellido.setText("¿Cual es tu apellido?");

        BT_Comenzar.setText("Comenzar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB_Bienvenido1)
                            .addComponent(LB_Bienvenido2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(LB_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TF_Nombre)
                                        .addComponent(TF_Apellido)
                                        .addComponent(LB_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(LB_Bienvenido3)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(BT_Comenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 317, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(LB_Bienvenido1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LB_Bienvenido2)
                .addGap(18, 18, 18)
                .addComponent(LB_Bienvenido3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LB_Nombre)
                .addGap(9, 9, 9)
                .addComponent(TF_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(LB_Apellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BT_Comenzar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Comenzar;
    private javax.swing.JLabel LB_Apellido;
    private javax.swing.JLabel LB_Bienvenido1;
    private javax.swing.JLabel LB_Bienvenido2;
    private javax.swing.JLabel LB_Bienvenido3;
    private javax.swing.JLabel LB_Nombre;
    private javax.swing.JTextField TF_Apellido;
    private javax.swing.JTextField TF_Nombre;
    // End of variables declaration//GEN-END:variables
}
