/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Componentes.FrameRecrea;
import Contrato.ContratoBotones;
import Controller.ControllerConsultar;
import Controller.Estadistica;
import Model.Objetos.Actividad;
import Model.Objetos.Persona;
import java.awt.event.ActionEvent;
import java.util.List;

/**
 *
 * @author Manuel Goncalves L.
 */
public class Avance extends FrameRecrea implements ContratoBotones {

    private final ControllerConsultar cc;
    private final List<Actividad> actividades;
    private final Estadistica estadistica;
    //private Persona persona;
    /**
     * Creates new form Avance
     * @param persona usuario que se examinará para dar los resultados del avance obtenido
     */
    public Avance(Persona persona) {
        initComponents();
        estadistica=new Estadistica(persona.getActividades());
        this.LB_DiaMasProductivo.setText(estadistica.GetDiaMasProductivo());
        this.LB_DiaMenosProductivo.setText(estadistica.GetDiaMenosProductivo());
        this.LB_UltimaPractica.setText(estadistica.GetUltimaConexion());
        this.LB_EjerciciosRealizados.setText(Integer.toString(estadistica.GetEjerciciosRealizados()));
        this.LB_PuntosObtenidos.setText(Integer.toString(estadistica.GetPuntosObtenidos()));
        this.LB_PuntosTotales.setText(Integer.toString(estadistica.GetPuntosTotales()));
        this.LB_NotaGeneral.setText(Integer.toString(estadistica.GetNota()));
        this.LB_PromEjercicios.setText(estadistica.GetPromPracticaDiaria());
        this.configuracion(PN_Contenedor);
        cc=new ControllerConsultar();
        actividades=cc.CargarActividades();
        this.LB_Usuario.setText(persona.getNombre()+" "+persona.getApellido());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PN_Contenedor = new Componentes.PanelRecrea();
        botonSalirRecrea1 = new Componentes.BotonSalirRecrea(this,true);
        labelRecrea1 = new Componentes.LabelRecrea();
        LB_Usuario = new Componentes.LabelRecrea();
        labelRecrea3 = new Componentes.LabelRecrea();
        labelRecrea4 = new Componentes.LabelRecrea();
        labelRecrea5 = new Componentes.LabelRecrea();
        labelRecrea6 = new Componentes.LabelRecrea();
        labelRecrea7 = new Componentes.LabelRecrea();
        labelRecrea8 = new Componentes.LabelRecrea();
        LB_PuntosObtenidos = new Componentes.LabelRecrea();
        LB_DiaMenosProductivo = new Componentes.LabelRecrea();
        LB_DiaMasProductivo = new Componentes.LabelRecrea();
        LB_PromEjercicios = new Componentes.LabelRecrea();
        LB_EjerciciosRealizados = new Componentes.LabelRecrea();
        LB_UltimaPractica = new Componentes.LabelRecrea();
        labelRecrea15 = new Componentes.LabelRecrea();
        labelRecrea16 = new Componentes.LabelRecrea();
        LB_PuntosTotales = new Componentes.LabelRecrea();
        LB_NotaGeneral = new Componentes.LabelRecrea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelRecrea1.setText("Estudiante:");

        LB_Usuario.setText("labelRecrea2");

        labelRecrea3.setText("Última práctica:");

        labelRecrea4.setText("Ejercicios realizados:");

        labelRecrea5.setText("Probabilidad de práctica diaria:");

        labelRecrea6.setText("Día mas productivo:");

        labelRecrea7.setText("Día menos productivo:");

        labelRecrea8.setText("Puntos obtenidos:");

        LB_PuntosObtenidos.setText("labelRecrea9");

        LB_DiaMenosProductivo.setText("labelRecrea10");

        LB_DiaMasProductivo.setText("labelRecrea11");

        LB_PromEjercicios.setText("labelRecrea12");

        LB_EjerciciosRealizados.setText("labelRecrea13");

        LB_UltimaPractica.setText("labelRecrea14");

        labelRecrea15.setText("Puntos totales:");

        labelRecrea16.setText("Nota general:");

        LB_PuntosTotales.setText("labelRecrea17");

        LB_NotaGeneral.setText("labelRecrea18");

        javax.swing.GroupLayout PN_ContenedorLayout = new javax.swing.GroupLayout(PN_Contenedor);
        PN_Contenedor.setLayout(PN_ContenedorLayout);
        PN_ContenedorLayout.setHorizontalGroup(
            PN_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_ContenedorLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PN_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PN_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PN_ContenedorLayout.createSequentialGroup()
                            .addComponent(labelRecrea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(161, 161, 161)
                            .addComponent(LB_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(PN_ContenedorLayout.createSequentialGroup()
                            .addGroup(PN_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelRecrea8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelRecrea7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelRecrea6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelRecrea5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelRecrea4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelRecrea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelRecrea15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelRecrea16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(PN_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LB_PuntosObtenidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LB_DiaMenosProductivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LB_DiaMasProductivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LB_PromEjercicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LB_EjerciciosRealizados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LB_UltimaPractica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LB_PuntosTotales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LB_NotaGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(botonSalirRecrea1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 41, Short.MAX_VALUE))
        );
        PN_ContenedorLayout.setVerticalGroup(
            PN_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN_ContenedorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PN_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRecrea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PN_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRecrea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_UltimaPractica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PN_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRecrea4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_EjerciciosRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PN_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRecrea5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_PromEjercicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PN_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRecrea6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_DiaMasProductivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PN_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRecrea7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_DiaMenosProductivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PN_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRecrea8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_PuntosObtenidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PN_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRecrea15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_PuntosTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PN_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRecrea16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_NotaGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(botonSalirRecrea1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN_Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PN_Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Avance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Avance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Avance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Avance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Avance(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Componentes.LabelRecrea LB_DiaMasProductivo;
    private Componentes.LabelRecrea LB_DiaMenosProductivo;
    private Componentes.LabelRecrea LB_EjerciciosRealizados;
    private Componentes.LabelRecrea LB_NotaGeneral;
    private Componentes.LabelRecrea LB_PromEjercicios;
    private Componentes.LabelRecrea LB_PuntosObtenidos;
    private Componentes.LabelRecrea LB_PuntosTotales;
    private Componentes.LabelRecrea LB_UltimaPractica;
    private Componentes.LabelRecrea LB_Usuario;
    private Componentes.PanelRecrea PN_Contenedor;
    private Componentes.BotonSalirRecrea botonSalirRecrea1;
    private Componentes.LabelRecrea labelRecrea1;
    private Componentes.LabelRecrea labelRecrea15;
    private Componentes.LabelRecrea labelRecrea16;
    private Componentes.LabelRecrea labelRecrea3;
    private Componentes.LabelRecrea labelRecrea4;
    private Componentes.LabelRecrea labelRecrea5;
    private Componentes.LabelRecrea labelRecrea6;
    private Componentes.LabelRecrea labelRecrea7;
    private Componentes.LabelRecrea labelRecrea8;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ActionSiguiente(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void ActionSalir(ActionEvent e) {
     this.setVisible(false);
     this.dispose();
    }

    @Override
    public void ActionOpciones(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void ActionSonido(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
