/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author Manuel
 */
public class Ejercicio extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio
     */
    
    private int cantEjercicios=3;//cantidad de ejercicios a realizar por prueba
    private int contEjercicios=0;//contador de la cantidad de ejercicios realizados
    private JPanel PN_Menu=new JPanel(new GridLayout(3, 1, 10, 10));
    private JPanel PN_OpcionesSup=new JPanel(new GridLayout(1,3,10,10));
    private JPanel PN_OpcionesInf=new JPanel(new GridLayout(1,3,10,10));
    private JPanel PN_Contenido=new JPanel(new GridLayout(1,1,0,0));
    private JPanel PN_OpcionesEjer=new JPanel(new GridLayout(1,3,10,10));
    JLabel a1= new JLabel(),a2= new JLabel(),a3= new JLabel(),b= new JLabel(),c1= new JLabel(),c2= new JLabel(),c3= new JLabel();
    JButton b1=new JButton(),b2=new JButton(),b3=new JButton(),salir=new JButton("SALIR"),seguir=new JButton("SEGUIR");
    

    
    public Ejercicio() {
        initComponents();
        this.setLayout(new GridLayout(3,1));
        GridBagConstraints c = new GridBagConstraints();
        
        a1.setText("1 de 3");
        a1.setHorizontalAlignment(SwingConstants.CENTER);
        
        b.setText("CONTENIDO");
        b.setBackground(Color.yellow);

        a2.setText("Pepito Perez");
        a2.setHorizontalAlignment(SwingConstants.CENTER);

        a3.setText("Altavoz");
        a3.setHorizontalAlignment(SwingConstants.CENTER);
       
        
        PN_OpcionesSup.add(a1);
        PN_OpcionesSup.add(a2);
        PN_OpcionesSup.add(a3);
        
        this.add(PN_OpcionesSup);
        
        PN_Contenido.add(b,SwingConstants.CENTER);
        this.add(PN_Contenido);
        
        PN_OpcionesEjer.add(b1);
        PN_OpcionesEjer.add(b2);
        PN_OpcionesEjer.add(b3);
  

        PN_OpcionesInf.add(salir);
        PN_OpcionesInf.add(PN_OpcionesEjer);
        PN_OpcionesInf.add(seguir);
        this.add(PN_OpcionesInf);
    }
 private void cargarPanel(JPanel contenedor, JPanel contenedorHijo)
    {
        // Se definen los tamanos iniciales de cada uno
        final Dimension tamanoContenedorPrincipalInicial = contenedor.getPreferredSize().getSize(); // Contenedor que albergara al otro
        final Dimension tamanoFormularioInicial = contenedorHijo.getPreferredSize().getSize(); // El hijo, el JPanel donde será puesto
 
        // Borramos cualquier cosa que pueda haber en el contenedor padre
        contenedor.removeAll();
 
        // Tamano del contenedor que va a tener a los q se le meta
        Dimension nuevoTamano = new Dimension(tamanoFormularioInicial.width, tamanoFormularioInicial.height); // Le ponemos el tamano de lo que albergara y la altura correspondiente
        contenedor.setPreferredSize(nuevoTamano); // Se le asigna ese nuevo tamaño
 
        // Anadimos al contenedor el JPanel llamado al contenedor y lo ponemos visible (por defecto no son visibles, hay que ponerlos)
        contenedor.add(contenedorHijo).setVisible(true);
 
        this.pack(); // Hacemos esto para que se reestructure el JFrame principal y autoajuste su tamano a lo que contiene dentro
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
