package View;

import Componentes.FrameRecrea;
import Componentes.PanelRecrea;
import Contrato.ContratoBotones;
import Contrato.ContratoGeneral;
import Controller.ControllerConsultar;
import Controller.Util;
import Controller.WindosCreate;
import Model.Objetos.Materia;
import Model.Objetos.Persona;
import java.awt.event.ActionEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdom2.JDOMException;




/**
 *
 * @author Manuel
 */
public class Inicio extends FrameRecrea implements ContratoGeneral,ContratoBotones{

    private PanelRecrea PN_Botones;
    private List<Materia> materias;
    private String ruta=Controller.Util.ARCHIVOS_XML_PATH+Util.MATERIAS_TAG+Util.ARCHIVO_XML;
    private Persona usuario;
    private Modulos Child;
    
    public Inicio() throws JDOMException {
   
        initComponents(); 
        ControllerConsultar info=new ControllerConsultar(ruta);
        materias=info.cargarMateria();
        WindosCreate wc=new WindosCreate(materias.size(),this);
        PN_Botones=wc.mostrarBot(materias, PN_Botones);
        this.configuracion(PN_Botones);
        this.fullScreen();
        MB_Recrea.setContrato(this); //para aseignar los ActionListener
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MB_Recrea = new Componentes.MenuBarRecrea(this);
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("File");
        MB_Recrea.add(jMenu3);

        jMenu4.setText("Edit");
        MB_Recrea.add(jMenu4);

        setJMenuBar(MB_Recrea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                   if(Controller.ControllerCrear.consultarUsuario())
                       new Inicio().setVisible(true);
                else{
                       new AgregarUsuario().setVisible(true);
                   }
                } catch (JDOMException ex) {
                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Componentes.MenuBarRecrea MB_Recrea;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    // End of variables declaration//GEN-END:variables


    @Override
    public void ActionSiguiente(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void ActionSalir(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void ActionOpciones(ActionEvent ae) {
              if(this.isVisible())
        {
        System.out.println(ae.getActionCommand());
       // Modulos Child= new Modulos();
        for(int i=0;i<materias.size();i++){
            if(ae.getActionCommand()==materias.get(i).getNombre()){
                usuario=new Persona();
                Child= new Modulos(materias.get(i).getHijoURL(),materias.get(i), usuario);
                break;
            }
        }
        Child.setVisible(true);
        this.setVisible(false);
        this.dispose();
        } 
    }

    @Override
    public void ActionSonido(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void SetEnable(boolean bol){
       this.SetEnable(bol);
    }

    @Override
    public void Reaload() {
    this.paintAll(this.getGraphics());  
    this.revalidate();
   }
}

