/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Componentes.Audio;
import Componentes.FrameRecrea;
import Controller.Util;
import Model.Objetos.Actividad;
import Model.Objetos.Persona;
import Model.Objetos.Respuesta;
import java.awt.event.ActionEvent;
import java.io.IOException;

/**
 * Clase que contiene los resultados obtenidos tras realizar los ejercicios previamente
 * muestra la respuesta realizada y el resultado de aprobacio o no del ejercicio
 * @author Manuel Goncalves L.
 */
public class Resultados extends FrameRecrea implements Contrato.ContratoBotones{

    private final Persona persona;
    private final int contador;
    private final Respuesta respuesta;
    private final Modulos modulos;
    private final Actividad actividad;//actividad realizada
    
    /**
     * Constructor
     * @param md Interfaz Módulo para poder retornar a ella
     * @param pers usuario que está realizando el ejercicio
     * @param cont contador para controlar cual es el resultado que se esta mostrando
     */
    public Resultados(Modulos md,Persona pers,int cont)  {
        initComponents();
        modulos=md;
        contador=cont;
        persona=pers;
        TA_Pregunta.setEditable(false);
        TA_Pregunta.SetConfigText();
       
        //se obtiene la ultima actividad la cual es la que se acabo de realizar
        int ultimaActividad=persona.getActividades().size()-1;
        actividad=persona.getActividades().get(ultimaActividad);
        respuesta=actividad.GetRespuesta().get(cont);
        this.fullScreen();
        this.configuracion(PN_Content);
        this.add(PN_Content);
        this.LB_CantEjerc.setText((cont+1)+Util.SEPARADOR_DE+actividad.GetRespuesta().size());
        this.LB_Usuario.setText(pers.getNombre()+" "+pers.getApellido());
        this.TA_Pregunta.setText(respuesta.GetPregunta());
        this.LB_RespuestaRealizada.setText(respuesta.GetRespuestaRealizada());
        this.LB_RespuestaCorrecta.setText(respuesta.GetRespuestaCorrecta());
        try{
            
        if(respuesta.GetRespuestaCorrecta().trim().equals("")){
            this.LB_Aprobado.setText(Util.DIALOG_MENSAJE_NOAPLICA);
            this.BT_Calificacion.BotonConfig(Util.IMAGEN_CARITA_FELIZ,Util.BOTON_TIPO_CARITA);
        }else
        if(respuesta.EsCorrecta()){
            this.LB_Aprobado.setText(Util.DIALOG_MENSAJE_APROBADA);
            this.BT_Calificacion.BotonConfig(Util.IMAGEN_CARITA_FELIZ,Util.BOTON_TIPO_CARITA);
            Audio sonido=new Audio(Util.RUTA_SONIDO_CORRECTO);
            sonido.Play();
            
        }
        else{
            this.LB_Aprobado.setText(Util.DIALOG_MENSAJE_FALLIDO);
            this.BT_Calificacion.BotonConfig(Util.IMAGEN_CARITA_TRISTE,Util.BOTON_TIPO_CARITA);
            Audio sonido=new Audio(Util.RUTA_SONIDO_EQUIVOCADO);
            sonido.Play();
        }
        }
        catch(Exception ex){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PN_Content = new Componentes.PanelRecrea();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_Pregunta = new Componentes.TAreaRecrea();
        PN_Contenido = new Componentes.PanelRecrea();
        LB_RespuestaCorrectaT = new Componentes.LabelRecrea();
        LB_PreguntaT = new Componentes.LabelRecrea();
        LB_RespuestaCorrecta = new Componentes.LabelRecrea();
        LB_RespuestaRealizada = new Componentes.LabelRecrea();
        LB_RespuestaRealizadaT = new Componentes.LabelRecrea();
        LB_Aprobado = new Componentes.LabelRecrea();
        BT_Salir = new Componentes.BotonSalirRecrea(this,true);
        LB_CantEjerc = new Componentes.LabelRecrea();
        LB_Usuario = new Componentes.LabelRecrea();
        BT_Calificacion = new Componentes.BotonRecrea();
        botonSeguirRecrea1 = new Componentes.BotonSeguirRecrea(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(TA_Pregunta);

        LB_RespuestaCorrectaT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LB_RespuestaCorrectaT.setText("Respuesta Correcta:");

        LB_PreguntaT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LB_PreguntaT.setText("Respuesta Realizada:");

        LB_RespuestaCorrecta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LB_RespuestaCorrecta.setText("labelRecrea5");

        LB_RespuestaRealizada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LB_RespuestaRealizada.setText("labelRecrea6");

        LB_RespuestaRealizadaT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LB_RespuestaRealizadaT.setText("¿Aprobado?");

        LB_Aprobado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LB_Aprobado.setText("labelRecrea4");

        javax.swing.GroupLayout PN_ContenidoLayout = new javax.swing.GroupLayout(PN_Contenido);
        PN_Contenido.setLayout(PN_ContenidoLayout);
        PN_ContenidoLayout.setHorizontalGroup(
            PN_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_ContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PN_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LB_RespuestaRealizadaT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LB_RespuestaCorrectaT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LB_PreguntaT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PN_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_Aprobado, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(LB_RespuestaRealizada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LB_RespuestaCorrecta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PN_ContenidoLayout.setVerticalGroup(
            PN_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_ContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PN_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_PreguntaT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LB_RespuestaRealizada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(PN_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_RespuestaCorrectaT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LB_RespuestaCorrecta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(PN_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_RespuestaRealizadaT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LB_Aprobado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        LB_CantEjerc.setText("labelRecrea7");

        LB_Usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB_Usuario.setText("labelRecrea8");

        javax.swing.GroupLayout PN_ContentLayout = new javax.swing.GroupLayout(PN_Content);
        PN_Content.setLayout(PN_ContentLayout);
        PN_ContentLayout.setHorizontalGroup(
            PN_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_ContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PN_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PN_ContentLayout.createSequentialGroup()
                        .addComponent(LB_CantEjerc, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                        .addGap(117, 117, 117)
                        .addComponent(LB_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN_ContentLayout.createSequentialGroup()
                        .addGroup(PN_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PN_ContentLayout.createSequentialGroup()
                                .addComponent(BT_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonSeguirRecrea1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PN_ContentLayout.createSequentialGroup()
                                .addComponent(PN_Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(BT_Calificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        PN_ContentLayout.setVerticalGroup(
            PN_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN_ContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PN_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_CantEjerc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LB_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PN_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PN_Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_Calificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(PN_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSeguirRecrea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(TA_Pregunta);
        jScrollPane1.getViewport().setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PN_Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PN_Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultados(null,null,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Componentes.BotonRecrea BT_Calificacion;
    private Componentes.BotonSalirRecrea BT_Salir;
    private Componentes.LabelRecrea LB_Aprobado;
    private Componentes.LabelRecrea LB_CantEjerc;
    private Componentes.LabelRecrea LB_PreguntaT;
    private Componentes.LabelRecrea LB_RespuestaCorrecta;
    private Componentes.LabelRecrea LB_RespuestaCorrectaT;
    private Componentes.LabelRecrea LB_RespuestaRealizada;
    private Componentes.LabelRecrea LB_RespuestaRealizadaT;
    private Componentes.LabelRecrea LB_Usuario;
    private Componentes.PanelRecrea PN_Contenido;
    private Componentes.PanelRecrea PN_Content;
    private Componentes.TAreaRecrea TA_Pregunta;
    private Componentes.BotonSeguirRecrea botonSeguirRecrea1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ActionSiguiente(ActionEvent e) {
    if(contador<actividad.GetRespuesta().size()-1){
    Resultados result=new Resultados(this.modulos,this.persona,this.contador+1);

    result.setVisible(true);
   }
    else{
     modulos.setVisible(true);
    // persona.resetActividades();
    }
    this.setVisible(false);
     this.dispose();
    }

    @Override
    public void ActionSalir(ActionEvent e) {
      this.setVisible(false);
      modulos.setVisible(true);
    //  this.persona.resetActividades();
      this.dispose();
    }

    @Override
    public void ActionOpciones(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void ActionSonido(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
